version: "3.1"

services:
  db:
    container_name: mongodb
    image: mongo:latest
    restart: always
    volumes:
      - ./expressTS:/data/db
    environment:
      - MONGO_INITDB_DATABASE=yourDbName
    ports:
      - 27018:27017